### ISSUE TITLE
Emmet behaves weirdly if using unicode icons on content

### ISSUE THREAD

**Issue by Simillo** [emmetio/emmet#459] opened 2016-07-24 13:15 UTC
Emmet shortcuts such as "m0" for 

```
margin: 0;
```

acts like 

```
mmargin: ;
```

and incrementing/decrementing shortcut "ctrl + arrow key up/down" works like:

```
margin: 20px;
```

to

```
margin: 221x;
```

then to

```
margin: 2222;
```

This happens if the previous selector has content of "📞". 

Eg.:

```
li:before {
  content: "📞";
}

/*Emmet shortcuts will not work on
any selector after the "content" */  

div {
  mmargin: ;
  /* p20 */
  ppadding: 2px;
}
```

**Comment by sergeche** [comment] 2019-08-20 20:03
Duplicate of #541

**Closed by sergeche** 2019-08-20 20:03 UTC
