### ISSUE TITLE
Support for Gedit 3+

### ISSUE THREAD

**Issue by ms10398** [emmetio/emmet#524] opened 2017-12-25 14:27 UTC
Is there any plugin available for latest gedit update.

When searching I found out that there was one [plugin](https://github.com/fmarcia/zen-coding-gedit) which supported till gedit 3 for Python 2.7 but not above.

Can we have a update on the gedit plugin

**Comment by sergeche** [comment] 2019-08-20 20:20
Duplicate of #202

**Closed by sergeche** 2019-08-20 20:20 UTC
Labels: Plugin
