### ISSUE TITLE
Endless loop in lib\parser\css.js:186 - eatString

### ISSUE THREAD

**Issue by alexandrudima** [emmetio/emmet#453] opened 2016-06-25 20:14 UTC
From microsoft/vscode#8135

When the cursor is at the pipe (`|`), expanding the abbreviation for the following content:

``` css
.test {
|white-space: pre-line;"
}
```

will cause an endless loop in `lib\parser\css.js:186 - eatString`.

`eatString` enters when `walker` was at the end of the line, at the double quote.

Evaluating `w.source.replace(/\n/g,'\\n').replace(/\r/g, '\\r')`: `\r\nwhite-space: pre-line;"`

![image](https://cloud.githubusercontent.com/assets/5047891/16358841/24e51e66-3b21-11e6-99b0-e59d99aa4588.png)

**Comment by mrmlnc** [comment] 2016-07-04 23:20
Either forgive the error by adding the checking for a value in a variable `c`.

```js
while (c && c !== q) { ... }
```

**Comment by miparnisari** [comment] 2016-10-07 14:01
Is there an ETA for this fix? VSCode hangs up on me multiple times a day because of this :(

**Comment by mrmlnc** [comment] 2016-11-03 09:06
Also reproduced with:

```less
.test {
  ct"|
}
```

**Comment by sergeche** [comment] 2016-11-03 09:57
No ETA yet, but started a project rewrite already, will fix it in a new version

**Comment by ramya-rao-a** [comment] 2016-12-15 17:52
This should be the same as #396 for which @rebornix has submitted a fix

**Comment by ramya-rao-a** [comment] 2016-12-30 18:45
@sergeche This is a duplicate of #396 which got fixed in the latest release, you can close this.

**Closed** 2017-01-21 09:53 UTC
Labels: bug
