### ISSUE TITLE
Emmet in SublimeText3 not works with UTF-8

### ISSUE THREAD

**Issue by Curiouslynx** [emmetio/emmet#544] opened 2018-10-16 08:48 UTC
Emmet in SublimeText3 doesn't works if document contains utf-8 symbols in `<pre>` tag.

Try using Emmet after:

`<pre>🔍</pre>`

**Comment by jluisgarcia** [comment] 2018-10-21 18:44
That is probably an issue for Sublime Text repository. Not Emmet.

**Comment by sergeche** [comment] 2019-08-20 18:47
Duplicate of #541

**Closed by sergeche** 2019-08-20 18:48 UTC
Labels: Editor-specific
